# Useful link: https://adamcod.es/2014/09/23/vagrant-ansible-quickstart-tutorial.html
---
- hosts: all
  sudo: true
  tasks:
    - name: Configure bash
      file: src={{ item.path }} dest={{ item.dest }} state=link force=yes
      with_items:
        - { path: /vagrant/ansible/bash/.bashrc, dest: /home/vagrant/.bashrc }
        - { path: /vagrant/ansible/bash/.bash_profile, dest: /home/vagrant/.bash_profile }
        - { path: /vagrant/ansible/bash/.bash_logout, dest: /home/vagrant/.bash_logout }
    - name: Configure vim.
      file: src=/vagrant/ansible/vim/.vimrc dest=/home/vagrant/.vimrc state=link force=yes

    - name: Update aptitude cache.
      apt: update_cache=yes
    - name: Upgrade all packages to latest (safe).
      apt: upgrade=safe

    - name: Authorize SSH from all my PCs.
      authorized_key: user=vagrant key=https://github.com/QuocAnhVu.keys

    - name: Set up Git.
      include: git.yml
    - name: Set up Node.js.
      include: node.yml
